version: '3'
services:
    server:
        container_name: typechase_backend
        image: node:15.5.1
        ports:
            - '80:80'
        volumes:
            - ./:/opt/src
        command: bash -c 'cd /opt/src && npm install && npm run build:front && npm run start:back'
        restart: allways
    redis:
        container_name: typechase_redis
        image: redis:5.0.3
        volumes:
            - ./var/docker/redis:/data
        restart: allways
