version: '3'
services:
    app:
        container_name: typechase_frontend
        image: node:15.5.1
        ports:
            - '8080:8080'
        volumes:
            - ./:/opt/src
        command: bash -c 'cd /opt/src && npm install && npm run dev:front'
    server:
        container_name: typechase_backend
        image: node:15.5.1
        ports:
            - '8003:3003'
            - '8002:3002'
        volumes:
            - ./:/opt/src
        command: bash -c 'cd /opt/src && npm install && npm run dev:back'
    redis:
        container_name: typechase_redis
        image: redis:5.0.3
        volumes:
            - ./var/docker/redis:/data
