version: '3'
services:
    server:
        container_name: typechase_backend
        image: node:15.5.1
        ports:
            - '80:80'
            - '8000:8000'
            - '443:443'
        volumes:
            - ./:/opt/src
            - /etc/letsencrypt/live/typechase.pennanen.dev:/letsencrypt
        command: bash -c 'cd /opt/src && npm install && NODE_ENV=production npm run build:front && NODE_ENV=production npm run start:back'
        restart: unless-stopped
    redis:
        container_name: typechase_redis
        image: redis:5.0.3
        volumes:
            - ./var/docker/redis:/data
        restart: unless-stopped
